In [15]:
import numpy as np
import pandas as pd

In [16]:
for k in range(1,16):
    a=str(k)
    ofile="Data as txt Files\sub"+a+".txt"
    print(ofile)
    with open(ofile, 'r') as f:
        lines = f.readlines()
    l=[]
    for i in range(len(lines)):
        lines[i] = lines[i].lstrip()
    sfile="modified_data\sub"+a+".txt"
    with open(sfile, 'w') as f:
        f.writelines(lines)

<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:10: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:10: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Athul\AppData\Local\Temp\ipykernel_5644\124062365.py:3: SyntaxWarning: invalid escape sequence '\s'
  ofile="Data as txt Files\sub"+a+".txt"
C:\Users\Athul\AppData\Local\Temp\ipykernel_5644\124062365.py:10: SyntaxWarning: invalid escape sequence '\s'
  sfile="modified_data\sub"+a+".txt"

Data as txt Files\sub1.txt
Data as txt Files\sub2.txt
Data as txt Files\sub3.txt
Data as txt Files\sub4.txt
Data as txt Files\sub5.txt
Data as txt Files\sub6.txt
Data as txt Files\sub7.txt
Data as txt Files\sub8.txt
Data as txt Files\sub9.txt
Data as txt Files\sub10.txt
Data as txt Files\sub11.txt
Data as txt Files\sub12.txt
Data as txt Files\sub13.txt
Data as txt Files\sub14.txt
Data as txt Files\sub15.txt

In [17]:
import sys
np.set_printoptions(threshold=sys.maxsize)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000) # Widen the display area
pd.set_option('display.max_colwidth', None) # Ensure full content in columns 
my_array_1 = np.loadtxt("modified_data/sub1.txt")
df_sub1=pd.DataFrame(my_array_1,columns=[f'Ch{i+1}' for i in range(8)])
df_sub1.to_csv("modified_data/sub1.csv", index=False)
my_array_2 = np.loadtxt("modified_data/sub2.txt")
df_sub2=pd.DataFrame(my_array_2,columns=[f'Ch{i+1}' for i in range(8)])
df_sub2.to_csv("modified_data/sub2.csv", index=False)
my_array_3 = np.loadtxt("modified_data/sub3.txt")
df_sub3=pd.DataFrame(my_array_3,columns=[f'Ch{i+1}' for i in range(8)])
df_sub3.to_csv("modified_data/sub3.csv", index=False)
my_array_4 = np.loadtxt("modified_data/sub4.txt")
df_sub4=pd.DataFrame(my_array_4,columns=[f'Ch{i+1}' for i in range(8)])
df_sub4.to_csv("modified_data/sub4.csv", index=False)
my_array_5 = np.loadtxt("modified_data/sub5.txt")
df_sub5=pd.DataFrame(my_array_5,columns=[f'Ch{i+1}' for i in range(8)])
df_sub5.to_csv("modified_data/sub5.csv", index=False)
my_array_6 = np.loadtxt("modified_data/sub6.txt")
df_sub6=pd.DataFrame(my_array_6,columns=[f'Ch{i+1}' for i in range(8)])
df_sub6.to_csv("modified_data/sub6.csv", index=False)
my_array_7 = np.loadtxt("modified_data/sub7.txt")
df_sub7=pd.DataFrame(my_array_7,columns=[f'Ch{i+1}' for i in range(8)])
df_sub7.to_csv("modified_data/sub7.csv", index=False)
my_array_8 = np.loadtxt("modified_data/sub8.txt")
df_sub8=pd.DataFrame(my_array_8,columns=[f'Ch{i+1}' for i in range(8)])
df_sub8.to_csv("modified_data/sub8.csv", index=False)
my_array_9 = np.loadtxt("modified_data/sub9.txt")
df_sub9=pd.DataFrame(my_array_9,columns=[f'Ch{i+1}' for i in range(8)])
df_sub9.to_csv("modified_data/sub9.csv", index=False)
my_array_10 = np.loadtxt("modified_data/sub10.txt")
df_sub10=pd.DataFrame(my_array_10,columns=[f'Ch{i+1}' for i in range(8)])
df_sub10.to_csv("modified_data/sub10.csv", index=False)
my_array_11 = np.loadtxt("modified_data/sub11.txt")
df_sub11=pd.DataFrame(my_array_11,columns=[f'Ch{i+1}' for i in range(8)])
df_sub11.to_csv("modified_data/sub11.csv", index=False)
my_array_12 = np.loadtxt("modified_data/sub12.txt")
df_sub12=pd.DataFrame(my_array_12,columns=[f'Ch{i+1}' for i in range(8)])
df_sub12.to_csv("modified_data/sub12.csv", index=False)
my_array_13 = np.loadtxt("modified_data/sub13.txt")
df_sub13=pd.DataFrame(my_array_13,columns=[f'Ch{i+1}' for i in range(8)])
df_sub13.to_csv("modified_data/sub13.csv", index=False)
my_array_14 = np.loadtxt("modified_data/sub14.txt")
df_sub14=pd.DataFrame(my_array_14,columns=[f'Ch{i+1}' for i in range(8)])
df_sub14.to_csv("modified_data/sub14.csv", index=False)
my_array_15 = np.loadtxt("modified_data/sub15.txt")
df_sub15=pd.DataFrame(my_array_15,columns=[f'Ch{i+1}' for i in range(8)])
df_sub15.to_csv("modified_data/sub15.csv", index=False)

In [18]:
print(f"Shape of DataFrame in memory: {df_sub1.shape}")

Shape of DataFrame in memory: (24085, 8)

In [19]:
df_sub2.tail(5)

        Ch1   Ch2   Ch3  Ch4   Ch5   Ch6   Ch7   Ch8
24098 -21.0  14.0  -1.0  5.0  19.0 -44.0 -33.0 -41.0
24099  24.0  -1.0  11.0  9.0  21.0  28.0  15.0  30.0
24100  14.0  19.0   1.0 -5.0   7.0   5.0  29.0   6.0
24101   5.0 -18.0  -1.0 -4.0 -25.0 -70.0 -34.0  19.0
24102  11.0 -33.0   5.0 -6.0 -10.0 -48.0  -8.0 -26.0

In [20]:
l=[df_sub1,df_sub2,df_sub3,df_sub4,df_sub5,
   df_sub6,df_sub7,df_sub8,df_sub9,df_sub10,
   df_sub11,df_sub12,df_sub13,df_sub14,df_sub15]
final_df=pd.concat(l)

In [21]:
final_df.head()

    Ch1   Ch2   Ch3  Ch4   Ch5   Ch6   Ch7   Ch8
0  -2.0  15.0   6.0 -4.0  -8.0 -16.0 -85.0 -95.0
1 -36.0 -41.0  24.0 -8.0 -15.0 -99.0 -88.0  -6.0
2 -10.0  29.0 -17.0  8.0  13.0  99.0  72.0  44.0
3  41.0 -10.0 -27.0 -6.0  -4.0 -11.0 -17.0 -34.0
4  -1.0   6.0   6.0 -6.0  -6.0 -31.0   1.0 -61.0

In [22]:
final_df.describe()

                 Ch1            Ch2            Ch3            Ch4            Ch5            Ch6            Ch7            Ch8
count  361257.000000  361257.000000  361257.000000  361257.000000  361257.000000  361257.000000  361257.000000  361257.000000
mean       -0.579715      -0.441663      -0.479188      -0.488054      -0.465259      -2.215343      -1.821598      -2.975740
std        42.838828      30.871504      18.513413      19.392876      22.401135      53.579804      45.996974      56.649522
min      -128.000000    -128.000000    -128.000000    -128.000000    -128.000000    -128.000000    -128.000000    -128.000000
25%       -26.000000     -17.000000      -9.000000     -10.000000     -11.000000     -35.000000     -27.000000     -41.000000
50%        -1.000000       0.000000       0.000000      -1.000000      -1.000000      -3.000000      -2.000000      -4.000000
75%        24.000000      16.000000       8.000000       8.000000       9.000000      29.000000      23.000000      34.000000
max       127.000000     127.000000     127.000000     127.000000     127.000000     127.000000     127.000000     127.000000

In [23]:
final_df.to_csv("modified_data/final_data.csv",index=False)